### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by RedaRafi** [pxiangwu/MotionNet#10]
python train_multi_seq.py --data /DataSet/ --batch 8 --nepoch 45 --nworker 4 --use_bg_tc --reg_weight_bg_tc 0.1 --use_fg_tc --reg_weight_fg_tc 2.5 --use_sc --reg_weight_sc 15.0 --log

Namespace(batch=8, data='/DataSet/', log=True, logpath='', nepoch=45, nn_sampling=False, nworker=4, reg_weight_bg_tc=0.1, reg_weight_fg_tc=2.5, reg_weight_sc=15.0, resume='', use_bg_tc=True, use_fg_tc=True, use_sc=True)
device number 1
data root: /DataSet/
Training dataset size: 17065
Epoch 1, learning rate 0.0016
Traceback (most recent call last):
  File "train_multi_seq.py", line 610, in <module>
    main()
  File "train_multi_seq.py", line 183, in main
    = train(model, criterion, trainloader, optimizer, device, epoch)
  File "train_multi_seq.py", line 226, in train
    motion_pred, trans_matrices, pixel_instance_map)
  File "train_multi_seq.py", line 356, in compute_and_bp_loss
    loss.backward()
  File "/home/redrafi/.local/lib/python3.7/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/redrafi/.local/lib/python3.7/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

#-------------------------------------------- My Env details-----------------------------------------------------------------
# Name                ---    Version  ----                 Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             4.5                       1_gnu
blas                      1.0                         mkl
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2021.7.5             h06a4308_1
cachetools                4.2.2              pyhd8ed1ab_0    conda-forge
cairo                     1.16.0               hf32fb01_1
certifi                   2021.5.30        py37h06a4308_0
cffi                      1.14.5           py37h261ae71_0
cudatoolkit               9.0                  h13b8566_0
cycler                    0.10.0                   py37_0
dbus                      1.13.18              hb2f20db_0
expat                     2.4.1                h2531618_2
ffmpeg                    4.0                  hcdf2ecd_0
fontconfig                2.13.1               h6c09931_0
freeglut                  3.2.1                h9c3ff4c_2    conda-forge
freetype                  2.10.4               h5ab3b9f_0
glib                      2.68.2               h36276a3_0
graphite2                 1.3.13            h58526e2_1001    conda-forge
gst-plugins-base          1.14.0               h8213a91_2
gstreamer                 1.14.0               h28cd5cc_2
harfbuzz                  1.8.8                hffaf4a1_0
hdf5                      1.10.2               hc401514_3    conda-forge
icu                       58.2                 he6710b0_3
intel-openmp              2021.2.0           h06a4308_610
jasper                    2.0.14               h07fcdf6_1
joblib                    0.17.0                     py_0    anaconda
jpeg                      9b                   h024ee3a_2
kiwisolver                1.3.1            py37h2531618_0
lcms2                     2.12                 h3be6417_0
ld_impl_linux-64          2.35.1               h7274673_9
libblas                   3.9.0                     9_mkl    conda-forge
libcblas                  3.9.0                     9_mkl    conda-forge
libffi                    3.3                  he6710b0_2
libgcc-ng                 9.3.0               h5101ec6_17
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.3.0                hdf63c60_0    anaconda
libglu                    9.0.0             he1b5a44_1001    conda-forge
libgomp                   9.3.0               h5101ec6_17
liblapack                 3.9.0                     9_mkl    conda-forge
libopencv                 3.4.2                hb342d67_1
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.37               hbc83047_0
libstdcxx-ng              9.3.0               hd4cf53a_17
libtiff                   4.2.0                h85742a9_0
libuuid                   1.0.3                h1bed415_2
libvpx                    1.7.0                h439df22_0
libwebp-base              1.2.0                h27cfd23_0
libxcb                    1.14                 h7b6447c_0
libxml2                   2.9.12               h03d6c58_0
llvmlite                  0.36.0           py37hf484d3e_0    numba
lz4-c                     1.9.3                h2531618_0
matplotlib                3.3.4            py37h06a4308_0
matplotlib-base           3.3.4            py37h62a2d02_0
mkl                       2021.2.0           h06a4308_296
mkl-service               2.3.0            py37h27cfd23_1
mkl_fft                   1.3.0            py37h42c9631_2
mkl_random                1.2.1            py37ha9443f7_2
ncurses                   6.2                  he6710b0_1
ninja                     1.10.2               hff7bd54_1
numba                     0.53.1          np1.11py3.7h04863e7_g97fe221b3_0    numba
numpy                     1.21.0           py37h038b26d_0    conda-forge
olefile                   0.46                     py37_0
opencv                    3.4.2            py37h6fd60c2_1
openssl                   1.1.1k               h27cfd23_0
pcre                      8.45                 h295c915_0
pillow                    8.0.0            py37h9a89aac_0    anaconda
pip                       21.1.3           py37h06a4308_0
pixman                    0.40.0               h36c2ea0_0    conda-forge
py-opencv                 3.4.2            py37hb342d67_1
pycparser                 2.20                       py_2
pyparsing                 2.4.7              pyhd3eb1b0_0
pyqt                      5.9.2            py37h05f1152_2
pyquaternion              0.9.9                    pypi_0    pypi
python                    3.7.10               h12debd9_4
python-dateutil           2.8.1              pyhd3eb1b0_0
python_abi                3.7                     2_cp37m    conda-forge
pytorch                   1.1.0           py3.7_cuda9.0.176_cudnn7.5.1_0    pytorch
qt                        5.9.7                h5867ecd_1
quaternion                2021.6.9.13.34.11  py37h5e8e339_0    conda-forge
readline                  8.1                  h27cfd23_0
scikit-learn              0.23.2           py37h0573a6f_0    anaconda
scipy                     1.6.2            py37had2a1c9_1
setuptools                52.0.0           py37h06a4308_0
sip                       4.19.8           py37hf484d3e_0
six                       1.16.0             pyhd3eb1b0_0
sqlite                    3.36.0               hc218d9a_0
threadpoolctl             2.1.0              pyh5ca1d4c_0    anaconda
tk                        8.6.10               hbc83047_0
torchvision               0.3.0           py37_cu9.0.176_1    pytorch
tornado                   6.1              py37h27cfd23_0
tqdm                      4.61.1             pyhd8ed1ab_0    conda-forge
tzdata                    2021a                h52ac0ba_0
wheel                     0.36.2             pyhd3eb1b0_0
xorg-fixesproto           5.0               h7f98852_1002    conda-forge
xorg-inputproto           2.3.2             h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxfixes            5.0.3             h7f98852_1004    conda-forge
xorg-libxi                1.7.10               h7f98852_0    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h7b6447c_0
zlib                      1.2.11               h7b6447c_3
zstd                      1.4.9                haebb681_0

**Comment by pxiangwu** [comment]
Hi, not sure why this error occurred. Did you modify the code somewhere? Were you able to successfully run `train_single_seq.py`?

**Comment by RedaRafi** [comment]
> Hi, not sure why this error occurred. Did you modify the code somewhere? Were you able to successfully run `train_single_seq.py`?

i didn't change noting in the code am runnig :
python train_multi_seq.py --data ./DataSet/ --batch 8 --nepoch 45 --nworker 4 --use_bg_tc --reg_weight_bg_tc 0.1 --use_fg_tc --reg_weight_fg_tc 2.5 --use_sc --reg_weight_sc 15.0 --log

**Comment by RedaRafi** [comment]
i think the problem was in the cmd i tried 
python train_multi_seq.py --data ./DataSet/ 
and it works 
![image](https://user-images.githubusercontent.com/64382788/124847480-7c5eca80-df8a-11eb-91ed-027ad32a1163.png)
