### ISSUE TITLE
hello! When I run the gen_data.py, it has a problem in LidarPointCloud(from nuscenes.utils.data_classes import LidarPointCloud)

### ISSUE THREAD

**Issue by zhouwy-lv** [pxiangwu/MotionNet#13]
Traceback (most recent call last):
  File "E:/MotionNet/MotionNet/data/gen_data.py", line 401, in <module>
    gen_data()
  File "E:/MotionNet/MotionNet/data/gen_data.py", line 83, in gen_data
    LidarPointCloud.from_file_multisweep_bf_sample_data(nusc, curr_sample_data,
AttributeError: type object 'LidarPointCloud' has no attribute 'from_file_multisweep_bf_sample_data'

It seen that the class of LidarPointCloud don't have  'from_file_multisweep_bf_sample_data'

**Comment by cuiDarchan** [comment]
Hello，I encountered the same problem. How did you solve it ？ 3Q

**Comment by cuiDarchan** [comment]
> Traceback (most recent call last): File "E:/MotionNet/MotionNet/data/gen_data.py", line 401, in gen_data() File "E:/MotionNet/MotionNet/data/gen_data.py", line 83, in gen_data LidarPointCloud.from_file_multisweep_bf_sample_data(nusc, curr_sample_data, AttributeError: type object 'LidarPointCloud' has no attribute 'from_file_multisweep_bf_sample_data'
> 
> It seen that the class of LidarPointCloud don't have 'from_file_multisweep_bf_sample_data'
Hello，I encountered the same problem. How did you solve it ？ 3Q

**Comment by pxiangwu** [comment]
Hello,

The class `LidarPointCloud` inherits class `PointCloud`, and the method `from_file_multisweep_bf_sample_data` can be found [here](https://github.com/KleinYuan/MotionNet/blob/master/nuscenes-devkit/python-sdk/nuscenes/utils/data_classes.py#L279).

Have you added the `nuscenes-devkit` to the PYTHONPATH, like this?
```
export PYTHONPATH=/home/pwu/PycharmProjects/MotionNet:$PYTHONPATH
export PYTHONPATH=/home/pwu/PycharmProjects/MotionNet/nuscenes-devkit/python-sdk:$PYTHONPA
```

**Comment by cuiDarchan** [comment]
> Hello,
> 
> The class `LidarPointCloud` inherits class `PointCloud`, and the method `from_file_multisweep_bf_sample_data` can be found [here](https://github.com/KleinYuan/MotionNet/blob/master/nuscenes-devkit/python-sdk/nuscenes/utils/data_classes.py#L279).
> 
> Have you added the `nuscenes-devkit` to the PYTHONPATH, like this?
> 
> ```
> export PYTHONPATH=/home/pwu/PycharmProjects/MotionNet:$PYTHONPATH
> export PYTHONPATH=/home/pwu/PycharmProjects/MotionNet/nuscenes-devkit/python-sdk:$PYTHONPA
> ```

3Q, I got it!
