### ISSUE TITLE
if other datasets can be used by this model

### ISSUE THREAD

**Issue by cracker-Li** [pxiangwu/MotionNet#16]
Hello!
I wanna know if other datasets can be used by this model.
Is it feasible to convert the annotation file into nuScenes format? 
I think rewriting the dataset import may be a solution.

**Comment by pxiangwu** [comment]
Hello,

Other datasets can be used by this model. A feasible way is to convert the annotation of your datasets into the format of nuScenes.

**Comment by cracker-Li** [comment]
Thank you！I will have a try.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pxiangwu/MotionNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月5日(星期天) 下午3:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pxiangwu/MotionNet] if other datasets can be used by this model (Issue #16)





 
Hello,
 
Other datasets can be used by this model. A feasible way is to convert the annotation of your datasets into the format of nuScenes.
