### ISSUE TITLE
Some questions about background_temporal_consistency loss

### ISSUE THREAD

**Issue by kwwcv** [pxiangwu/MotionNet#17]
Hi @pxiangwu ,
Thanks for your open sources, I am just wondering why flipping curr_pred along dim=2 before applying F.affine_grid in function **background_temporal_consistency_loss**
```
# Next, translation
curr_pred = curr_pred.permute(0, 1, 3, 2).contiguous()  # swap x and y axis 
curr_pred = torch.flip(curr_pred, dims=[2]) 

grid = F.affine_grid(grid_trans_matrix_disp, curr_pred.size())
```

**Comment by pxiangwu** [comment]
Hi @kwwcv, honestly I do not remember clearly. But I think this is due to some coordinate change and make sure the x and y axis align with the target coordinate.

**Comment by kwwcv** [comment]
Thanks!
