### ISSUE TITLE
split.npy file for the smaller nuscenes v1.0-mini dataset

### ISSUE THREAD

**Issue by cuihenggang** [pxiangwu/MotionNet#2]
Hi,

I am trying to play with the MotionNet model on the smaller nuscenes `v1.0-mini` dataset. Could you please tell me how to generate the split.npy file for a new dataset?

Thank you very much!

Henggang

**Comment by pxiangwu** [comment]
Hi,

Actually `split.npy` is just a python `Dictionary`. It has three keys: 'train', 'val', 'test'. For each key, e.g., 'train', it contains a list of scenes, such as 'scene_1', 'scene_2', etc. 

So, for nuscenes `v1.0-mini`, you could manually create a python dictionary like this:
```
data = dict()
test_list = np.array(['scene_1', 'scene_2', 'scene_3', 'scene_4'])
train_list = np.array(['scene_5', 'scene_6', 'scene_7', 'scene_8'])
val_list = np.array(['scene_9', 'scene_10'])

data['train'] = train_list
data['test'] = test_list
data['val'] = val_list

np.save('small_split.npy', data)
```

**Comment by cuihenggang** [comment]
Sounds good. Thank you very much!
