### ISSUE TITLE
Inactive bug in classify_speed_level

### ISSUE THREAD

**Issue by demmerichs** [pxiangwu/MotionNet#8]
In the following snippet I added an assertion with a `NOTE` comment. Is it correct?
The assertion never throws, that is why I described this as an inactive bug ;)

```python
def classify_speed_level(
    all_disp_field_gt, total_future_sweeps=20, future_frame_skip=0
):
    """
    Classify each cell into static (possibly background) or moving.
    """
    # First, compute the static and moving cell masks
    all_disp_field_gt_norm = np.linalg.norm(all_disp_field_gt, ord=2, axis=-1)

    # Every future_frame_skip frames, if the movement of grid cells does not exceed this thresh (unit: meters),
    # then they are considered as static. This thresh is set to be the maximum perturbation for 1 second.
    upper_thresh = 0.2
    upper_bound = (future_frame_skip + 1) / 20 * upper_thresh
    selected_future_sweeps = np.arange(
        0, total_future_sweeps + 1, future_frame_skip + 1
    )
    selected_future_sweeps = selected_future_sweeps[1:]

    assert (
        future_frame_skip == 0
    )  # NOTE: the following selection does only work if no frames were skipped
    future_sweeps_disp_field_gt_norm = all_disp_field_gt_norm[
        -len(selected_future_sweeps) :, ...
    ]
    ...
```

**Comment by pxiangwu** [comment]
Hi @DavidS3141 

This is actually not a bug. I would prefer to call this "code that needs to improve" or "ugly code" :joy:

What I did is just hardcoded the parameter `future_frame_skip` to be 0, and wrote all the code in `classify_speed_level` following this logic. 

And yes, currently we can add the assertion as you mentioned `assert (future_frame_skip == 0)` to ensure this.

This code could be improved in the future to consider the cases when `future_frame_skip != 0`.

Thanks a lot for pointing out this. :+1:
